title: me site
author: you know it
email: jimbo@here.com
description: > # this means to ignore newlines until "baseurl:"
  the chillest site with the chillest dudes

# social links
twitter_username: donthave one
github_username:  ricemagician

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
